version: "3.9"
services:
  api:
    build: ..
    working_dir: /app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8001
    env_file:
      - ../.env
    environment:
      - REDIS_URL=redis://redis:6379/0
    ports:
      - "8001:8001"
    volumes:
      - ..:/app:cached
    depends_on:
      - postgres
      - redis

  postgres:
    image: ankane/pgvector:pg15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bimo
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Optional (Phase 2+): Redis for Celery and caching
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  worker:
    build: ..
    working_dir: /app
    command: celery -A app.workers.celery_app worker --loglevel=INFO
    env_file:
      - ../.env
    environment:
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - ..:/app:cached
    depends_on:
      - redis
      - postgres

volumes:
  pg_data:
