name: CLI smoke test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}
  schedule:
    - cron: '0 4 * * *' # daily at 04:00 UTC

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install CLI runtime deps
        run: npm --prefix ./dist/cli install

      - name: Patch dist/cli package.json (set type:module)
        run: |
          # patch script is safe and exits 0 when dist/cli/package.json not present
          node scripts/patch_dist_cli_package.cjs || true

      - name: Prepare service account (from secret)
        env:
          SA_JSON: ${{ secrets.SA_JSON }}
        run: |
          if [ -z "${SA_JSON}" ]; then
            echo "No SA_JSON secret provided; skipping smoke test" && exit 78
          fi
          echo "$SA_JSON" > /tmp/sa.json

      - name: Run smoke test
        env:
          BIMO_GATEWAY: ${{ secrets.BIMO_GATEWAY }}
          SA_PATH: /tmp/sa.json
        run: |
          chmod +x ./scripts/cli_smoke_test.sh
          ./scripts/cli_smoke_test.sh

  full_e2e:
    name: Full E2E (protected)
    runs-on: ubuntu-latest
    # Require a protected environment to run this job (create 'e2e' in repo settings)
    environment: e2e
    # Only run if SA_JSON secret is present (guard)
    if: ${{ secrets.SA_JSON != '' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install CLI runtime deps
        run: npm --prefix ./dist/cli install

      - name: Patch dist/cli package.json (set type:module)
        run: |
          node scripts/patch_dist_cli_package.cjs || true

      - name: Prepare service account (from secret)
        env:
          SA_JSON: ${{ secrets.SA_JSON }}
        run: |
          if [ -z "${SA_JSON}" ]; then
            echo "No SA_JSON secret provided; skipping full E2E" && exit 78
          fi
          echo "$SA_JSON" > /tmp/sa.json

      - name: Run full E2E smoke test
        env:
          BIMO_GATEWAY: ${{ secrets.BIMO_GATEWAY }}
          SA_PATH: /tmp/sa.json
        run: |
          chmod +x ./scripts/cli_smoke_test.sh
          ./scripts/cli_smoke_test.sh


