name: CLI smoke test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install CLI from npm
        run: |
          # Install published CLI package so smoke tests run against the published artifact.
          # Attempt to install the package by name; falls back to latest if ref_name unavailable.
          npm install -g bimo-cli || npm install -g bimo-cli@latest

      - name: Patch dist/cli package.json (set type:module)
        run: |
          # patch script is safe and exits 0 when dist/cli/package.json not present
          node scripts/patch_dist_cli_package.cjs || true

      - name: Prepare service account (from secret)
        env:
          SA_JSON: ${{ secrets.SA_JSON }}
        run: |
          if [ -z "$SA_JSON" ]; then
            echo "No SA_JSON secret provided; skipping smoke test" && exit 78
          fi
          echo "$SA_JSON" > /tmp/sa.json

      - name: Run smoke test
        env:
          BIMO_GATEWAY: ${{ secrets.BIMO_GATEWAY }}
          SA_PATH: /tmp/sa.json
        run: |
          chmod +x ./scripts/cli_smoke_test.sh
          ./scripts/cli_smoke_test.sh


