name: Publish CLI

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Build CLI
        run: |
          # If a dist/cli package.json exists in the workspace, install its
          # runtime deps and use that artifact. Otherwise fall back to the
          # repository build script (legacy behavior).
          if [ -f "./dist/cli/package.json" ]; then
            echo "Found dist/cli/package.json — installing runtime deps"
            npm --prefix ./dist/cli install --production
          else
            echo "dist/cli not present — running repo build:cli"
            # Ensure the build script does not rely on ../bimo-backend and is
            # runnable in CI. If the CLI source lives in another repo, consider
            # checking it out here or moving the CLI source into this repo.
            npm run build:cli
          fi

      - name: Patch dist/cli package.json
        run: node scripts/patch_dist_cli_package.cjs || true

      - name: Publish to npm
        run: |
          cd dist/cli
          npm publish --access public



