name: Publish CLI

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Build CLI (packages/cli)
        run: |
          echo "Building CLI from packages/cli"
          cd packages/cli
          npm ci
          npm run build
          # ensure destination exists before copying
          mkdir -p ../../dist/cli
          cp -R dist ../../dist/cli

      - name: Patch dist/cli package.json
        run: node scripts/patch_dist_cli_package.cjs || true

      - name: Publish to npm
        run: |
          # Configure npm auth explicitly and verify identity before publishing
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
          npm whoami || (echo "npm auth failed" && exit 1)
          cd dist/cli
          npm publish --access public



